### ISSUE TITLE
Exceeding the github api rate limit

### ISSUE THREAD

**Issue by iandoesallthethings** [lorenzk/brew-cask-replacer#3]
Running this script is bonking against the API rate limit, even though I've created a new api token and stuck it in my shell config.

Even for the apps it seems to work on, they're not being added to my cask list when I use `brew list --casks`. Am I missing something?

**Comment by lorenzk** [comment]
Hi Ian! I have not thought about this project for years and cannot help you. However, if you do find a bug, I'll be happy to merge a pull request.
